services:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FIREBASE_API_KEY=AIzaSyBsQRyGq_jMVsw_Uyr_PNt3IYllj-fsEYQ
      - FIREBASE_AUTH_DOMAIN=charityfund-af2de.firebaseapp.com
      - FIREBASE_DATABASE_URL=https://charityfund-af2de-default-rtdb.firebaseio.com
      - FIREBASE_PROJECT_ID=charityfund-af2de
      - FIREBASE_STORAGE_BUCKET=charityfund-af2de.firebasestorage.app
    volumes:
      - ./frontend:/usr/src/app
      - ./backend:/usr/src/app

